Vampiro/views/PublicViews.py
# /Vampiro/views/PublicViews.py

from urllib.parse import unquote_plus
from flask import Blueprint, current_app, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user
from werkzeug.security import check_password_hash
import logging

from Vampiro.models.UserModel import User
from Vampiro.models.NewsletterModel import Cronicas
from Vampiro.utils.forms import LoginForm, handle_form_errors, SignUpForm, EmailForm, NewPasswordForm
from Vampiro.utils.emails import send_confirmation_instructions_email, send_welcome_email, send_password_reset_instructions_email, send_password_changed_email
from Vampiro.services.users import add_user, confirm_user, update_password
from Vampiro.utils.security import handle_exceptions, verify_confirmation_token, verify_reset_token

logger = logging.getLogger('simple_logger')

public = Blueprint('public', __name__)



@public.route('/')
@public.route('/home')
@handle_exceptions
def home():
    return render_template('public/home.html')

@public.route('/normas')
@handle_exceptions
def normas():
    return render_template('public/normas.html')

@public.route('/cronicas')
@handle_exceptions
def cronicas():
    cronicas = Cronicas.query.order_by(Cronicas.date.desc()).all()
    return render_template('public/cronicas.html', cronicas=cronicas)

# LOGIN _________________________________________________________________

@public.route('/login', methods=['GET','POST'])
@handle_exceptions
def login():

    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate_on_submit():

        user = User.query.filter_by(id=form.room.data).first()

        if user and check_password_hash(user.password_hashed, form.password.data):
            if user.confirmed:
                login_user(user, remember=form.remember_me.data)
                logger.info('Usuario %s ha iniciado sesión', user)
                return redirect(request.args.get('next') or url_for('profile.role_selector'))
            else:
                flash('Por favor confirma tu correo antes de iniciar sesión.', 'success')
                send_confirmation_instructions_email(user)
                return redirect(url_for('public.resend_confirmation'))
        else:
            flash('Usuario o contraseña incorrectos', 'danger')
    else:
        handle_form_errors(form)

    return render_template('public/signup_and_login/login.html', form=form)

@public.route('/logout')
@handle_exceptions
def logout():

    logout_user()
    flash('Has cerrado sesión. ¡Chao pescao!', 'success')

    return redirect(url_for('public.home'))

# SIGN UP _____________________________________________________________________

@public.route('/signup', methods=['GET', 'POST'])
@handle_exceptions
def signup():
    form = SignUpForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        new_user = add_user(form)
        logger.info('Nuevo usuario añadido: %s', new_user)
        send_confirmation_instructions_email(new_user)
        flash('Te has registrado con éxito. Por favor, confirma tu correo.', 'success')
        return redirect(url_for('public.home'))
    else:
        handle_form_errors(form)

    return render_template('public/signup_and_login/signup.html', form=form)

@public.route('/resend-confirmation', methods=['GET', 'POST'])
@handle_exceptions
def resend_confirmation():
    
    form = EmailForm()
    if request.method=='POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if user.confirmed:
                flash ('Mejor más que menos, pero tu cuenta ya estaba confirmada. No hacer falta RE-confirmar. ¡Puedes iniciar sesión si quieres!', 'success')
                return redirect(url_for('public.login'))
            else:
                logger.info('Usuario %s ha solicitado reenviar las instrucciones de confirmacion', user)
                send_confirmation_instructions_email(user)
                flash('Se han reenviado las instrucciones de confirmación a tu correo.', 'success')
    else:
        handle_form_errors(form)
    return render_template('public/signup_and_login/pending_activation.html', form=form)

@public.route('/confirm/<token>')
@handle_exceptions
def confirm(token):

    decoded_token = unquote_plus(token)
    user = verify_confirmation_token(decoded_token)
    if not user:
        return redirect(url_for('public.resend_confirmation'))
    if user.confirmed:
        flash ('Mejor más que menos, pero tu cuenta ya estaba confirmada. No hace falta RE-confirmar. ¡Puedes iniciar sesión si quieres!', 'success')
        return redirect(url_for('public.login'))
    else:
        confirm_user(user)
        logger.info('Usuario %s ha confirmado su cuenta', user)
        flash ('Acabas de confrimar tu cuenta... ¡Qué guay!', 'success')
        send_welcome_email(user)
            
    return redirect(url_for('public.home'))

# RESET PASSWORD ______________________________________________________________

@public.route('/reset-password', methods=['GET', 'POST'])
@handle_exceptions
def reset_password():

    form = EmailForm() #Reset password form

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            logger.info('Usuario %s ha solicitado cambiar su contraseña', user)
            send_password_reset_instructions_email(user)
            flash('Por favor comprueba tu correo. Has recibido un link para cambiar tu contraseña', 'success')
        else:
            flash('No hay ningún usuario con ese email', 'danger')
        return redirect(url_for('public.home'))
    else:
        handle_form_errors(form)
    
    return render_template('public/reset/reset_password.html', form=form)

@public.route('/reset-password/<token>', methods=['GET', 'POST'])
@handle_exceptions
def reset_password_token(token):

    decoded_token = unquote_plus(token)
    user = verify_reset_token(decoded_token)

    if not user:
        return redirect(url_for('public.reset_password'))
    
    form = NewPasswordForm() #Reset password form

    if request.method == 'POST' and form.validate_on_submit():
        update_password(user, form)
        logger.info('Contraseña cambiada para el usuario %s', user)
        send_password_changed_email(user)
        flash('Tu contraseña ha sido cambiada.', 'success')
        return redirect(url_for('public.login'))
    else:
        handle_form_errors(form)

    return render_template('public/reset/reset_with_token.html', form=form, token=token)

Vampiro/templates/layout.html
{% from "macros.html" import nav_bar %}
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon"
        href="{{ url_for('static', filename='img/favicon.ico')}}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=VT323'>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>{% block title %}{% endblock %}</title>
</head>


<body>
    {% block header %}
    {% endblock %}

    {% block navbar %}
      {{ nav_bar(current_user, user_role, game_status) }}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

Vampiro/templates/macros.html
{# Vampiro/templates/macros.html #}

{% macro nav_link(endpoint, text) -%}
{% if endpoint == request.endpoint %}
<a class="nav-link active" href="{{ url_for(endpoint) }}">{{ text }}<span class="sr-only">(current)</span></a>
{% else %}
<a class="nav-link" href="{{ url_for(endpoint) }}">{{ text }}</a>
{% endif %}
{%- endmacro %}


{% macro nav_bar(current_user, user_role, game_status) -%}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('public.home')}}"><img
      src="{{ url_for('static', filename='img/logo_juegos_pequeñito.png') }}" width="60" height="60"
      class="d-inline-block align-top" alt="Logo del aula de juegos"></span>
    <a class="navbar-brand mb-0 h1" href="{{ url_for('public.home')}}">Vampiro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          {{ nav_link('public.home', 'Home') }}
        </li>
        <li class="nav-item">
          {{ nav_link('public.cronicas', 'Crónicas') }}
        </li>
        <li class="nav-item">
          {{ nav_link('public.normas', 'Normas') }}
        </li>

        {% if current_user.is_authenticated %}
            {% if user_role == "visitor" or  (user_role == "player" and game_status != "IN_PROGRESS")  %}
              <li class="nav-item">
                {{ nav_link('profile.role_selector', 'Jugar') }}
              </li>
            {% endif %}

            {% if user_role == "player" and game_status == "IN_PROGRESS" %}
              <li class="nav-item">
                {{ nav_link('profile.my_stats', 'Mis stats') }}
              </li>
              <li class="nav-item">
                {{ nav_link('profile.game_stats', 'Partida actual') }}
              </li>
            {% endif %}

            {% if user_role == "admin" %}
            <li class="nav-item">
              {{ nav_link('admin.dashboard', 'Dashboard') }}
            </li>
            <li class="nav-item">
              {{ nav_link('admin.cronicas', 'Nueva Crónica') }}
            </li>
            <li class="nav-item">
              {{ nav_link('admin.cazas', 'Cazas') }}
            </li>
            <li class="nav-item">
              {{ nav_link('admin.disputas', 'Disputas') }}
            </li>
            <li class="nav-item">
              {{ nav_link('admin.settings', 'Ajustes') }}
            </li>
            <li class="nav-item">
              {{ nav_link('admin.database_management', 'Database') }}
            </li>
          {% endif %}

        {% endif %}
            </ul>

    <div class="text-right">
      <ul class="navbar-nav ">
        {% if not current_user.is_authenticated %}
        <li class="mx-2 nav-item">
            <a class="nav-link" href="{{ url_for('public.signup') }}">Registro</a>
        </li>
        {% endif %}

        <li class="mx-2 nav-item">
          {% if current_user.is_authenticated %}
          <a class="btn btn-outline-light px-4" href="{{ url_for('public.logout')}}">Cerrar Sesión</a>
          {% else %}
          <a class="btn btn-outline-light px-4" href="{{ url_for('public.login')}}">Inicia Sesión</a>
          {% endif %}
        </li>
      </ul>
    </div>
</nav>
{%- endmacro %}


{% macro flash_messages() -%}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

{%- endmacro %}