Vampiro/views/ProfileViews.py
# /Vampiro/views/ProfileViews.py

import os
import logging
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user


from Vampiro.models.SettingsModel import GameStatus
from Vampiro.utils.emails import send_duel_started_email, send_hunt_success_email, send_victim_death_email

from Vampiro.utils.forms import DeathAccusationForm, DeathConfirmationForm, DuelResponseForm, RoleSelectorForm, OrganizerForm, handle_form_errors

from Vampiro.services.users import change_role
from Vampiro.services.settings import get_game_status, get_holidays, get_round_status
from Vampiro.services.game import get_last_prey, get_round_number, get_alive_players, get_general_number_round_kills, get_current_danger, get_current_hunt, get_number_round_kills, get_number_total_kills, new_death_accusation, get_death_accusation, get_duel_where_hunter, get_duel_where_prey, set_prey_initial_response, reached_agreement, finalise_duel, set_hunter_duel_response, set_prey_duel_response, hunter_wins, get_current_dispute_by_prey, get_current_dispute_by_hunter
from Vampiro.utils.security import handle_exceptions

logger = logging.getLogger('simple_logger')

profile = Blueprint('profile', __name__)

@profile.before_request
def check_game_status_and_role():
    """
    Redirects the user to the appropriate page based on the game status and the user's role.    
    """
    if not current_user.is_authenticated:
        return redirect(url_for('public.login'))

    game_status = get_game_status()
    role = current_user.role

    if role.name == 'admin':
        return redirect(url_for('admin.dashboard'))
    elif role.name == 'visitor' or game_status != GameStatus.IN_PROGRESS:
        if request.endpoint != 'profile.role_selector':
            return redirect(url_for('profile.role_selector'))
    elif role.name == 'player' and game_status == GameStatus.IN_PROGRESS:
        if request.endpoint == 'profile.role_selector':
            return redirect(url_for('profile.my_stats'))



# PROFILE ______________________________________________________________________________________

@profile.route('/', methods=['GET', 'POST'])
@profile.route('/role_selector', methods=['GET', 'POST'])
@handle_exceptions
def role_selector():
    role_selector_form = RoleSelectorForm()
    organizer_form = OrganizerForm()

    if role_selector_form.validate_on_submit() and role_selector_form.form_name.data == 'role_selector_form':
        role = role_selector_form.response.data
        if role == 'visitor':
            role_id = 3
            logger.info('User %s has selected the role of visitor', current_user)
        elif role == 'player':
            role_id = 2
            logger.info('User %s has selected the role of player', current_user)
        change_role(current_user, role_id)

        return redirect(url_for('profile.role_selector'))

    if organizer_form.validate_on_submit() and organizer_form.form_name.data == 'organizer_form':
        if organizer_form.password.data == os.getenv('ADMIN_CODE'):
            #id for admin role, using names was giving issues
            admin=1
            change_role(current_user, admin)
            logger.info('User %s has selected the role of organizer', current_user)
            return redirect(url_for('admin.dashboard'))
        else:
            flash('El código no es correcto', 'warning')
            return redirect(url_for('profile.role_selector'))
    else:
        handle_form_errors(organizer_form)
        
    return render_template('profile/role_selector.html', role_selector_form = role_selector_form, organizer_form = organizer_form)

# GAME ______________________________________________________________________________________

@profile.route('/my_stats')
@handle_exceptions
def my_stats():

    if current_user.player.alive == False:
        duel_response_form_hunter = DuelResponseForm()
        player = current_user.player

        last_prey = get_last_prey(player.id).user
        ronda = get_round_number()
        total_kills = get_number_total_kills(player.id)
        pending_disputes = {
            'death_accusation': get_death_accusation(last_prey.id),
            'duel': get_duel_where_hunter(player.id),
        }

        logger.info('Dead user %s is viewing their stats', current_user)
        return render_template('profile/my_stats_dead.html', duel_response_form_hunter=duel_response_form_hunter, player=player, last_prey=last_prey, ronda=ronda, total_kills=total_kills, pending_disputes=pending_disputes)

    else:
        # Form setup
        death_accusation_form = DeathAccusationForm()
        death_confirmation_form = DeathConfirmationForm()
        duel_response_form_hunter = DuelResponseForm()
        duel_response_form_prey = DuelResponseForm()

        # Passing data to template
        player = current_user.player
        hunter = get_current_danger(player.id).hunter.user
        prey = get_current_hunt(player.id).prey.user


        death_accusation = get_death_accusation(prey.id)
        duel = get_duel_where_prey(prey.id)

        if death_accusation is not None and death_accusation.hunt.hunter == player:
            on_hold = False
        elif duel is not None and duel.hunt.hunter == player:
            on_hold = False
        else:
            on_hold = death_accusation is not None or duel is not None

        holidays = get_holidays()

        ronda = get_round_number()
        kills = {
            'round': get_number_round_kills(ronda, player.id),
            'total': get_number_total_kills(player.id)
        }
        disputes = {
            'death_accusation_where_prey': get_death_accusation(player.id),
            'death_accusation_where_hunter': get_death_accusation(prey.id),
            'duel_where_hunter': get_duel_where_hunter(player.id),
            'duel_where_prey': get_duel_where_prey(player.id)
        }

        logger.info('Alive user %s is viewing their stats', current_user)
        return render_template('profile/my_stats.html', death_accusation_form=death_accusation_form, death_confirmation_form=death_confirmation_form, duel_response_form_hunter=duel_response_form_hunter, duel_response_form_prey=duel_response_form_prey, player=player, hunter=hunter, prey=prey, on_hold=on_hold, holidays=holidays, kills=kills, disputes=disputes)

@profile.route('/my_stats/death_accusation', methods=['POST'])
@handle_exceptions
def death_accusation():
    """
    Handles the form submission for the death accusation form.
    If the hunter informs of a murder, the victim will be asked over email to report.
    """
    logger.info('Death accusation route visited')
    form = DeathAccusationForm()
    player = current_user.player

    if form.validate_on_submit():
        new_death_accusation(player.id)
    return redirect(url_for('profile.my_stats'))

@profile.route('/my_stats/death_confirmation', methods=['POST'])
@handle_exceptions
def death_confirmation():
    """
    Handles the form submission for the death confirmation form.
    If the prey confirms the death, the hunter wins the dispute, gets a new hunt and emails are sent.
    If the prey denies the death, the hunter is informed and the dispute becomes a duel, its revision group is updated.
    """
    logger.info('Death confirmation route visited by %s', current_user)
    form = DeathConfirmationForm()
    player = current_user.player
    
    if form.confirmar.data:
        response = True
    elif form.desmentir.data:
        response = False



    if form.validate_on_submit():

        set_prey_initial_response(player.id, response)
        dispute = get_current_dispute_by_prey(player.id)

        if response == True:
            hunter_wins(dispute)
            hunter = dispute.hunt.hunter
            dead_victim = dispute.hunt.prey
            next_victim = get_current_hunt(hunter.id).prey
            send_hunt_success_email(hunter, next_victim)
            send_victim_death_email(dead_victim)
        elif response == False:
            dispute.set_revision_group()
            send_duel_started_email(dispute.hunt.hunter, dispute.revision_group)
    
    return redirect(url_for('profile.my_stats'))
    
@profile.route('/my_stats/duel_response', methods=['POST'])
@handle_exceptions
def duel_response():
    """
    Handles the form submission for the duel response form.
    If both players agree on the duel, the dispute is finalised.
    If not in time, it will be handled by the automatic revision every 12 hours."""

    logger.info('Duel response route visited')
    form = DuelResponseForm()

    if form.validate_on_submit():
        type = form.type.data
        if form.confirmar.data:
            response = True
        elif form.desmentir.data:
            response = False
        player = current_user.player

        if type == 'hunter':
            dispute = get_current_dispute_by_hunter(player.id)
            set_hunter_duel_response(dispute, response)
        elif type == 'prey':
            dispute = get_current_dispute_by_prey(player.id)
            set_prey_duel_response(dispute, response)


        if dispute.hunter_duel_response is not None and dispute.prey_duel_response is not None:
            finalise_duel(dispute)

    return redirect(url_for('profile.my_stats'))


@profile.route('/game_stats')
@handle_exceptions
def game_stats():

    jugadores_vivos = len(get_alive_players())
    ronda_actual = get_round_number()
    muertos_ronda =  get_general_number_round_kills(ronda_actual)

    return render_template('profile/game_stats.html', jugadores_vivos=jugadores_vivos, ronda_actual=ronda_actual, muertos_ronda=muertos_ronda)

Vampiro/templates/profile/game_stats.html
{% extends "layout.html" %}

{% block title %}Partida actual{% endblock %}

{% block header %}{% endblock %}

{% block navbar %}{{ super() }}{% endblock %}

{% block content %}

<section class="bg black-overlay">
    <div class="container my-5 py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">

          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-3 text-center">

              <div class="mb-md-5 mt-md-4 pb-3">

                <h1 class="m-2 p-3 pixel-text">GAME STATS</h1>

                <p class="m-2 p-3 h4 pixel-text"> Vampiros vivos: {{ jugadores_vivos }} <br> Ronda actual: {{ ronda_actual }} <br> Muertos esta ronda: {{ muertos_ronda }} </p>
                <p class="d-inline-block m-4 p-3 bg-danger text-white pixel-text" style="font-size: max(1.2vw, 12px)">La noche termina a las 00:00<br><br>Es posible que se postponga el inicio de la siguiente ronda 12 horas hasta que se resuelvan todas las disputas.</p>

                
              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
</section>

{% endblock %}

{% block footer %}{% endblock %}

Vampiro/templates/profile/my_stats.html
{% extends "layout.html" %}

{% block title %}Mis stats{% endblock %}

{% block header %}{% endblock %}

{% block navbar %}{{ super() }}{% endblock %}

{% block content %}

<section class="bg black-overlay">
    <div class="container.fluid my-5 py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div class="col-11 col-md-8 col-lg-6 col-xl-5 m-2">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-2">

                            <h1 class="fw-bold mb-2 text-uppercase">MIS STATS</h1>
                            <p class="text-white-50 mb-5">Bienvenido {{ player.user.name }} {{ player.id }} <br> Aquí puedes ver la información más relevante sobre tu partida.
                            </p>

                            <div>
                                <h3 class="my-3">Tu presa actual</h3>

                                {% if round_status.value == "PENDING" or round_status.value == "TO_BE_FINALISED" %}
                                    <p>Actualmente estamos procesando la última ronda y no tienes una víctima asignada.</p>
                                {% elif on_hold  %}
                                    <p>Tu víctima tiene asuntos pendientes con su cazador previo.<br>Espera a que se resuelvan para que puedas cazarla.</p>
                                {% elif holidays  %}
                                    <p>Estamos de vacaciones... Vampiro incluido. Descansa un poco y guarda fuerzas para la vuelta.</p>
                                {% else %}
                                    <p>Nombre: {{ prey.name }}</p>
                                    <p>Habitación: {{ prey.room }}</p>
                                    {% if disputes.duel_where_hunter is not none or disputes.death_accusation_where_hunter is not none %}
                                    <div class="alert alert-danger pixel-text h5" role="alert">Ya se ha iniciado una disputa.</div>                               
                                    {% elif disputes.duel_where_prey is not none or disputes.death_accusation_where_prey is not none %}
                                    <div class="alert alert-danger pixel-text h5" role="alert">Hasta que no se aclare si estás vivo no podrás matar.</div>
                                    {% else %}
                                    <form method="POST" action="{{ url_for('profile.death_accusation')}}">
                                        {{ death_accusation_form.csrf_token }}
                                        <button type="submit" name="response" value="True" class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text" style="font-size: max(1.2vw, 16px)">La he matado</button>
                                    </form>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <hr>
                            <div>
                                <h3 class="my-3">Asesinatos</h3>
                                <p>Durante esta ronda: {{ kills.round }}</p>
                                <p>Totales: {{ kills.total }}</p>
                                {% if kills.round == 0 %}
                                    <div class="alert alert-warning pixel-text h5" role="alert">¡Mata a alguien antes de que termine la ronda o morirás de inanición!</div>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-11 col-md-8 col-lg-6 col-xl-5 m-2">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-2">

                            <h1 class="fw-bold mb-2 text-uppercase">DISPUTAS</h1>
                            <p class="text-white-50 mb-5">¿Tienes alguna disputa activa?<br>¡Estate atento para que no
                                se te pase el tiempo!</p>

                            {% if disputes.death_accusation_where_prey is not none %}
                                <div>
                                    <h3 class="my-3">¿Has muerto?</h3>
                                    <p>Tu cazador dice que has muerto, ¿estás de acuerdo?</p>
                                    <form method="POST" action="{{ url_for('profile.death_confirmation') }}">
                                        {{ death_confirmation_form.csrf_token }}
                                        {{ death_confirmation_form.confirmar(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                        {{ death_confirmation_form.desmentir(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                    </form>
                                    <p>Tienes hasta las
                                    {% if disputes.death_accusation_where_prey.revision_group.name == "DAY" %}
                                        00:00
                                    {% else %}
                                        12:00
                                    {% endif %}
                                    para responder.</p>
                                </div>
                            {% endif %}

                            {% if disputes.death_accusation_where_hunter is not none and (disputes.duel_where_hunter is not none or disputes.duel_where_prey is not none) %}
                                <hr>
                            {% endif %}

                            {% if disputes.duel_where_hunter is not none or disputes.duel_where_prey is not none %}
                            <div>
                                <h1 class="my-3">DUELOS DE MEDIANOCHE</h1>

                                {% if disputes.duel_where_hunter is not none %}
                                <div>
                                    <h2 class="my-3 text-danger pixel-text">{{ player.user.name }} ({{player.room}}) y {{prey.name}} ({{prey.room}})</h2>
                                    <p>Parece que no os ponéis de acuerdo.<br>Tenéis hasta las 
                                        {% if disputes.duel_where_hunter.revision_group.name == "DAY" %}
                                            00:00
                                        {% else %}
                                            12:00
                                        {% endif %}
                                         para hablarlo.</p>
                                    <div class="alert alert-danger pixel-text h5" role="alert">¿Alguien se ha saltado las normas? Contacta a uno de los organizadores.</div>
                                    <p>Esta es vuestra última oportunidad.<br>Si no respondéis lo mismo a tiempo, el azar decidirá quién gana este duelo.</p>
                                    
                                    {% if disputes.duel_where_hunter.hunter_duel_response is none %}
                                        <h4>¿Has matado?</h4>
                                        <form method="POST" action="{{ url_for('profile.duel_response') }}">
                                            {{ duel_response_form_hunter.csrf_token }}
                                            <input type="hidden" name="type" value="hunter">
                                            {{ duel_response_form_hunter.confirmar(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                            {{ duel_response_form_hunter.desmentir(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                        </form>
                                    {% else %}
                                        <div class="alert alert-warning pixel-text h5" role="alert">
                                            <p> Hemos guardado tu respuesta: <br>
                                            {% if disputes.duel_where_hunter.hunter_duel_response == True %}
                                                SÍ, HE MATADO. <br>
                                            {% else %}
                                                NO HE MATADO. <br>
                                            {% endif %}
                                            Estamos esperando la respuesta de {{ prey.name }}.</p>
                                        </div>
                                    {% endif %}

                                </div>
                                {% endif %}

                                {% if disputes.duel_where_hunter is not none and disputes.duel_where_prey is not none %}
                                <hr>
                                {% endif %}

                                {% if disputes.duel_where_prey is not none %}
                                <div>
                                    <h2 class="my-3 text-danger pixel-text">{{hunter.name}} ({{hunter.room}}) y {{ player.user.name }} ({{ player.room }})</h2>
                                    <p>Parece que no os ponéis de acuerdo.<br>Tenéis hasta las 
                                        {% if disputes.duel_where_prey.revision_group.name == "DAY" %}
                                            00:00
                                        {% else %}
                                            12:00
                                        {% endif %}
                                         para hablarlo.</p>
                                    <div class="alert alert-danger pixel-text h5" role="alert">¿Alguien se ha saltado las normas?<br> NO CONTESTES AÚN. <br> Contacta a uno de los organizadores.</div>
                                    <p>Esta es vuestra última oportunidad.<br>Si no respondéis lo mismo, el azar decidirá quién gana este duelo.</p>
                                    {% if disputes.duel_where_prey.prey_duel_response is none %}
                                        <h4>¿Te han matado?</h4>
                                        <form method="POST" action="{{ url_for('profile.duel_response') }}">
                                            {{ duel_response_form_prey.csrf_token }}
                                            <input type="hidden" name="type" value="prey">
                                            {{ duel_response_form_prey.confirmar(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                            {{ duel_response_form_prey.desmentir(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                        </form>
                                    {% else %}
                                    <div class="alert alert-warning pixel-text h5" role="alert">
                                        <p> Hemos guardado tu respuesta: <br>
                                        {% if disputes.duel_where_prey.prey_duel_response == True %}
                                            SÍ, ME HAN MATADO. <br>
                                        {% else %}
                                            NO ME HAN MATADO. <br>
                                        {% endif %}
                                        Estamos esperando la respuesta de {{ hunter.name }}.</p>
                                    </div>
                                    {% endif %}

                                </div>
                                {% endif %}

                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

{% endblock %}

{% block footer %}{% endblock %}

Vampiro/templates/profile/my_stats_dead.html
{% extends "layout.html" %}

{% block title %}Mis stats{% endblock %}

{% block header %}{% endblock %}

{% block navbar %}{{ super() }}{% endblock %}

{% block content %}

<section class="bg black-overlay">
    <div class="container.fluid my-5 py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div class="col-11 col-md-8 col-lg-6 col-xl-5 m-2">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-2">

                            <h1 class="fw-bold mb-2 text-uppercase">MI VIDA PASADA</h1>
                            <p class="text-white-50 mb-5">Aquí puedes ver la información más relevante sobre tu partida.
                            </p>
                            <div>
                                <h3 class="my-3">Asesinatos</h3>
                                <p>Totales: {{ total_kills }}</p>

                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-11 col-md-8 col-lg-6 col-xl-5 m-2">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-2">

                            <h1 class="fw-bold mb-2 text-uppercase">ASUNTOS PENDIENTES</h1>
                            <p class="text-white-50 mb-5">¿Te quedaste a medias?<br>No descansarás hasta rendir cuentas.</p>

                            {% if pending_disputes.death_accusation is not none %}
                                <div>
                                    <h3 class="my-3">Tú última víctima aún no ha respondido</h3>
                                    <p>¿Surgirá un duelo? ¡Sería de lo más fantasmagórico</p>
                                    <p>Tiene hasta las
                                    {% if pending_disputes.death_accusation.revision_group.name == "DAY" %}
                                        00:00
                                    {% else %}
                                        12:00
                                    {% endif %}
                                    para responder.</p>
                                </div>
                            {% endif %}


                            {% if pending_disputes.duel is not none  %}
                            <div>
                                <h1 class="my-3">DUELO DE MEDIANOCHE</h1>

                                <div>
                                    <h2 class="my-3 text-danger pixel-text">{{ player.user.name }} ({{player.room}}) y {{last_prey.name}} ({{last_prey.room}})</h2>
                                    <p>Parece que no os ponéis de acuerdo.<br>Tenéis hasta las 
                                        {% if pending_disputes.duel.revision_group.name == "DAY" %}
                                            00:00
                                        {% else %}
                                            12:00
                                        {% endif %}
                                         para hablarlo.</p>
                                    <div class="alert alert-danger pixel-text h5" role="alert">¿Alguien se ha saltado las normas? Contacta a uno de los organizadores.</div>
                                    <p>Esta es vuestra última oportunidad.<br>Si no respondéis lo mismo a tiempo, el azar decidirá quién gana este duelo.</p>
                                    
                                    {% if pending_disputes.duel.hunter_duel_response is none %}
                                        <h4>¿Llegaste a matar?</h4>
                                        <form method="POST" action="{{ url_for('profile.duel_response') }}">
                                            {{ duel_response_form_hunter.csrf_token }}
                                            <input type="hidden" name="type" value="hunter">
                                            {{ duel_response_form_hunter.confirmar(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                            {{ duel_response_form_hunter.desmentir(class="d-inline-block m-4 px-5 btn-danger btn-lg pixel-text", style="font-size: max(1.2vw, 16px)") }}
                                        </form>
                                    {% else %}
                                        <div class="alert alert-warning pixel-text h5" role="alert">
                                            <p> Hemos guardado tu respuesta: <br>
                                            {% if pending_disputes.duel.hunter_duel_response == True %}
                                                SÍ, MATÉ. <br>
                                            {% else %}
                                                NO MATÉ. <br>
                                            {% endif %}
                                            Estamos esperando la respuesta de {{ last_prey.name }}.</p>
                                        </div>
                                    {% endif %}

                                </div>
                            </div>
                            {% endif %}

                            {% if pending_disputes.death_accusation is none and pending_disputes.duel is none %}
                                <div>
                                    <h4 class="my-3">Ya no te quedan ataduras con este mundo.</h4>
                                    <p>Solo te mantiene presente un profundo rencor.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

{% endblock %}

{% block footer %}{% endblock %}